defaults:
  - _self_

method: mean-teacher

train:
  total_epochs: 250
  validation_interval: 10
  rampup_epochs: 5

init:
  _target_: trainer.MeanTeacher
  supervised_criterion:
    _target_: torch.nn.MSELoss
  unsupervised_weight: 0.5
  ema_decay: 0.99
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.001
    weight_decay: 0.0005
  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: true
    T_max: 250