defaults:
  - _self_

method: supervised-ensemble

train:
  total_epochs: 250
  validation_interval: 10

init:
  _target_: trainer.SupervisedEnsemble
  supervised_criterion:
    _target_: torch.nn.MSELoss
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.01
    weight_decay: 0.001
  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: true
    T_max: 250